#define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS, UNICODE_MODE_WINDOWS, UNICODE_MODE_LINUX
// I didn't care for these animations
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_TWINKLE
// these are good
//#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
//#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL

// default is 17 and that is too slow
#define RGBLIGHT_VAL_STEP 34
