#!/usr/bin/env python3

import functools
import pathlib
import re
import sys
import string

FUNCTION_START_RE = re.compile(
        r"JAK_PROCESS_FUNCTION_OPEN[(](?P<number>[0-9]+)[)].*")
TYPE_RE = re.compile(
        r"JAK_TYPE_KEY[(]0b(?P<bits>[01]+), *(?P<keycode>[()A-Z_0-9]+) *, *.*[)]")
OTHER_STUFF_RE = re.compile(
        r'JAK_DO_OTHER[(]0b(?P<bits>[01]+), *"(?P<explanation>[^"]*)".*'
        )
UNICODE_RE = re.compile(
        r'JAK_TYPE_UNICODE[(]0b(?P<bits>[01]+), *"(?P<unicode_char>[^"]*)".*'
        )
CAPSABLE_RE = re.compile(
        r"JAK_TYPE_CAPSABLE[(]0b(?P<bits>[01]+), *(?P<keycode>[()A-Z_0-9]+) *[)]")
NUMBER_FN_RE = re.compile(
        r"JAK_NUMBER_OR_FN[(]0b(?P<bits>[01]+), *(?P<number>[0-9]) *[)]")
FUNCTION_END_RE = re.compile(
        r"JAK_PROCESS_FUNCTION_CLOSE")
JUST_INNOCENT_KEYCODE = re.compile(
        r"KC_(?P<etcetera>[A-Z0-9()_]+)")

QMK_TO_HUMAN = {
    "SLSH": "/",
    "LPRN": "(",
    "RPRN": ")",
    "ESC": "Escape",
    "LBRC": "[",
    "RBRC": "]",
    "GRV": "`",
    "TILD": "~",
    "TAB": "Tab",
    "EQL": "=",
    "PPLS": "+",
    "COMM": ",",
    "AT": "@",
    "QUES": "?",
    "DQT": '"',
    "MINS": "-",
    "LCBR": "{",
    "RCBR": "}",
    "DOT": ".",
    "QUOT": "'",
    "SCLN": ";",
    "EXLM": "!",
    "COLN": ":",
    "BSPC": "Backspace",
    "SPC": "Space",
    "ENT": "Enter",
    "AMPR": "&",
}
# Missing: #, $, %, *, ^, <, >, \, |

def normalize_array_len(arr, l, empty_entry):
    remainder = len(arr) % l
    if remainder == 0:
        return arr
    add = l - remainder
    for _ in range(add):
        arr.append(empty_entry)
    return arr

def main():
    cur_dir = pathlib.Path(__file__)
    cur_dir = cur_dir.absolute().parent
    source_file = str(cur_dir / "keymap.c")
    keybind_lines = []
    with open(source_file, "r") as f:
        keybind_lines = [i.strip() for i in f.readlines() if i.startswith("JAK")]
    if len(keybind_lines) == 0:
        raise Exception("Didn't find any keybinding lines")
    max_key = 0
    by_length = {}
    out_of_function = True
    cur_list = None
    all_list = []
    morse_code_map = {}
    for line in keybind_lines:
        start_match = FUNCTION_START_RE.search(line)
        type_match = TYPE_RE.search(line)
        other_match = OTHER_STUFF_RE.search(line)
        end_match = FUNCTION_END_RE.search(line)
        unicode_match = UNICODE_RE.search(line)
        capsable_match = CAPSABLE_RE.search(line)
        number_fn_match = NUMBER_FN_RE.search(line)
        better_name = None
        if out_of_function:
            if start_match:
                out_of_function = False
                l = int(start_match.groupdict()["number"])
                by_length[l] = []
                cur_list = by_length[l]
                if l > max_key:
                    max_key = l
                continue
        else:
            number = None
            if end_match:
                cur_list = None
                out_of_function = True
                continue
            g = {}
            if type_match:
                g = type_match.groupdict()
                content = g["keycode"]
                innocent = JUST_INNOCENT_KEYCODE.search(content)
                if innocent:
                    content = innocent.groupdict()["etcetera"]
            if other_match:
                g = other_match.groupdict()
                content = g["explanation"]
            if unicode_match:
                g = unicode_match.groupdict()
                content = g["unicode_char"]
            if capsable_match:
                g = capsable_match.groupdict()
                content = g["keycode"]
                innocent = JUST_INNOCENT_KEYCODE.search(content)
                if innocent:
                    content = innocent.groupdict()["etcetera"]
            if number_fn_match:
                g = number_fn_match.groupdict()
                content = g["number"]
                number = content
                if content == "0":
                    content = "0/fn(F10)/2fn(F20)"
                else:
                    content = f"{content}/fn(F{content})/2fn(F{int(content)+10})"
            bits = g["bits"]
            bits = bits.replace("1", "-")
            bits = bits.replace("0", ".")
            content = QMK_TO_HUMAN.get(content, content)
            info = (content, bits)
            cur_list.append(info)
            all_list.append(info)
            if number:
                morse_code_map[number] = bits
            else:
                morse_code_map[content] = bits
    sorted_by_content = sorted(all_list, key=functools.cmp_to_key(lambda x,y: x[0] < y[0]))
    print("# this file is generated by generate_guide.py")
    print("## By length of code")
    for idx in range(max_key+1):
        if idx not in by_length:
            continue
        print(f"### {idx}")
        print("| code | action | | code | action | | code | action |")
        print("|------|--------|-|------|--------|-|------|--------|")
        actions = by_length[idx]
        actions = normalize_array_len(actions, 3, ('', ''))
        actions = sorted(actions, key=functools.cmp_to_key(lambda x,y: x[0] < y[0]))
        for adx in range(0, len(actions)//3):
            a0, c0 = actions[adx]
            a1, c1 = actions[adx + (len(actions)//3)]
            a2, c2 = actions[adx + (2*(len(actions)//3))]
            print(f"| {c0} | {a0} | | {c1} | {a1} | | {c2} | {a2} |")
        print()
    sorted_by_content = normalize_array_len(sorted_by_content, 3, ("",""))

    # The alphabet looks good with 3 columns with 3 empty at the end
    the_alphabet = [
            i for i in string.ascii_uppercase
    ] + ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
    the_alphabet = [(morse_code_map[i[0]], i) for i in the_alphabet]
    the_alphabet.append( ("","") )
    the_alphabet.append( ("","") )
    the_alphabet.append( ("","") )

    print("## The Alphabet and Numbers")
    print("| code | action | | code | action | | code | action |")
    print("|------|--------|-|------|--------|-|------|--------|")
    for idx in range(0, len(the_alphabet)//3):
        c0, a0 = the_alphabet[idx]
        c1, a1 = the_alphabet[idx + len(the_alphabet)//3]
        c2, a2 = the_alphabet[idx + 2*len(the_alphabet)//3]
        print(f"|{c0}|{a0}||{c1}|{a1}||{c2}|{a2}|")
    print()

    symbols = [(morse_code_map[i], i) for _, i in QMK_TO_HUMAN.items()]
    symbols = normalize_array_len(symbols, 3, ("", ""))
    print("## Symbols and Special Keys")
    print("| code | action | | code | action | | code | action |")
    print("|------|--------|-|------|--------|-|------|--------|")
    for idx in range(0, len(symbols)//3):
        c0, a0 = symbols[idx]
        c1, a1 = symbols[idx + len(symbols)//3]
        c2, a2 = symbols[idx + 2*len(symbols)//3]
        print(f"|{c0}|{a0}||{c1}|{a1}||{c2}|{a2}|")


    print("## A Big ol' Table of all the Codes")
    print("| code | action | | code | action | | code | action |")
    print("|------|--------|-|------|--------|-|------|--------|")
    for idx in range(0, len(sorted_by_content)//3):
        a0, c0 = sorted_by_content[idx]
        a1, c1 = sorted_by_content[idx + (len(sorted_by_content)//3)]
        a2, c2 = sorted_by_content[idx + 2*(len(sorted_by_content)//3)]

        print(f"| {c0} | {a0} | | {c1} | {a1} | | {c2} | {a2} |")

    return 0

if __name__ == "__main__":
    sys.exit(main())
