RGB_MATRIX_CUSTOM_USER = yes
UNICODEMAP_ENABLE = yes

CFLAGS += -DDISABLE_RGB_MATRIX_ALPHAS_MODS \
          -DDISABLE_RGB_MATRIX_GRADIENT_UP_DOWN \
          -DDISABLE_RGB_MATRIX_BREATHING \
          -DDISABLE_RGB_MATRIX_BAND_SAT \
          -DDISABLE_RGB_MATRIX_BAND_VAL \
          -DDISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT \
          -DDISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL \
          -DDISABLE_RGB_MATRIX_BAND_SPIRAL_SAT \
          -DDISABLE_RGB_MATRIX_BAND_SPIRAL_VAL \
          -DDISABLE_RGB_MATRIX_CYCLE_ALL \
          -DDISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT \
          -DDISABLE_RGB_MATRIX_CYCLE_UP_DOWN \
          -DDISABLE_RGB_MATRIX_CYCLE_OUT_IN \
          -DDISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL \
          -DDISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON \
          -DDISABLE_RGB_MATRIX_DUAL_BEACON \
          -DDISABLE_RGB_MATRIX_CYCLE_PINWHEEL \
          -DDISABLE_RGB_MATRIX_CYCLE_SPIRAL \
          -DDISABLE_RGB_MATRIX_RAINBOW_BEACON \
          -DDISABLE_RGB_MATRIX_RAINBOW_PINWHEELS \
          -DDISABLE_RGB_MATRIX_RAINDROPS \
          -DDISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS \
          -DDISABLE_RGB_MATRIX_TYPING_HEATMAP \
          -DDISABLE_RGB_MATRIX_DIGITAL_RAIN \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS \
          -DDISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS \
          -DDISABLE_RGB_MATRIX_SPLASH \
          -DDISABLE_RGB_MATRIX_MULTISPLASH \
          -DDISABLE_RGB_MATRIX_SOLID_SPLASH \
          -DDISABLE_RGB_MATRIX_SOLID_MULTISPLASH
